title: 'Ahmad Husen'
baseURL: 'https://husen.id/'
languageCode: 'en-us'
menu:
  main:
    - identifier: home
      name: Home
      url: /
      params:
        icon: home
      weight: 1
    - identifier: about
      name: About
      url: /about/
      params:
        icon: user
      weight: 2
    - identifier: project
      name: Work
      url: /project/
      params:
        icon: code
      weight: 3
    - identifier: blog
      name: Blog
      url: /blog/
      params:
        icon: pencil-alt
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      params:
        icon: mail
      weight: 5
taxonomies:
  tag: tag
permalinks:
  blog: /blog/:year/:month/:day/:slug/
markup:
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2
paginate: 9
enableRobotsTXT: true
enableEmoji: true
params:
  description: 'My personal site, portfolio, and blog.'
  author: Ahmad Husen
  facebook: https://facebook.com/hapakaien
  github: https://github.com/hapakaien
  gitlab: https://gitlab.com/hapakaien
  linkedin: https://linkedin.com/in/ahmadhusen
  twitter: '@hapakaien'
