baseURL: 'https://husen.id/'
enableRobotsTXT: true
languageCode: 'en-us'
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: project
      name: Work
      url: /project/
      weight: 3
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 5
taxonomies:
  tag: tag
permalinks:
  blog: /blog/:year/:month/:day/:slug/
title: 'Ahmad Husen'
